# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'
google-ID: ''

menu:
- {name: 'Events', folder: 'pages', file: 'events.html'}
- {name: 'Press', folder: 'pages', file: 'press.html'}
- {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/khoparzi'}
- {icon: 'facebook', link: 'https://www.facebook.com/algoraveindia'}
- {icon: 'instagram', link: 'https://instagram.com/algorave_india'}
# - {icon: 'envelope', link: 'mailto:algo@khoparzi.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
